version: '3'
services: 
  grafana:
    image: grafana/grafana:latest
    container_name: Grafana-Monitor
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana/
  nginx:
    image: nginx:latest
    container_name: Nginx-Webserver
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  grafana_data: {}
